### PR TITLE
Add Support Laravel 6.0

### PR DESCRIPTION
**Pull request by khanhvu14**

### CODE REVIEW

**Comment by WillSewell** [comment]
I agree with this change in principal, but it looks like the tests are now failing with PHP 7.2.

**Comment by MECU** [comment]
Upgrading the `graham-campbell/analyzer` package resolves the test errors (but not the deprecation warnings):

```
"graham-campbell/analyzer": "^2.3",
```

**Comment by GrahamCampbell** [comment]
Isn't pusher already included in the laravel core now?

**Comment by WillSewell** [comment]
Yes, this library is deprecated for that reason. However I'm happy to merge version bumps and bugfixes if people are still using this.

**Comment by GrahamCampbell** [comment]
Doesn't look like this PR works. I'll prepare one that does. In the meanwhile, it would be great to get https://github.com/pusher/pusher-http-laravel/pull/61 merged.

**Comment by GrahamCampbell** [comment]
Here we go: https://github.com/pusher/pusher-http-laravel/pull/62. The other important fix, other than the correct versions in the composer.json file for some other dependencies, is not calling `array_only`, since it doesn't exist in Laravel 6.

**Pull request closed without merging**
