### PR TITLE
Fix link to StyleCI badge

### PR DESCRIPTION
**Pull request by WillSewell**

### CODE REVIEW

**Comment by WillSewell** [comment]
Low risk. Merging.

**Comment by GrahamCampbell** [comment]
This breaks the badge styling actually.

**Comment by WillSewell** [comment]
I don't think it does.. This is what I see on the README on the master branch:

screenshot 2019-02-08 at 17 33 25

What do you see?

**Comment by GrahamCampbell** [comment]
The StyleCI badge now has square corners and the flat style, but it used to look like the other badges.

**Comment by GrahamCampbell** [comment]
Compare this to before you PR:

image

**Pull request merged**
