### PR TITLE
Laravel 5.6 Support

### PR DESCRIPTION
**Pull request by ce-brex**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
No need to drop php 7.0 support?

**Comment by ce-brex** [comment]
It was dropped following the PR as mentioned in https://github.com/pusher/pusher-http-laravel/issues/31#issuecomment-366164326.

**Comment by ce-brex** [comment]
Travis didn't test 7.0 on that last build.

**Comment by kn100** [comment]
I'll test and merge tomorrow :)

**Comment by derekaug** [comment]
Waiting on this to update our application to 5.6, glad to see it's in the works and basically done. 👍

**Pull request merged**
